---
name: Build and Deploy React App to GitHub Pages
on:
  push:
    branches: [main]
  jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: npm install

      - name: Test
        run: npm run test

      - name: Deploy
        run: |
          git config --global user.name 'Slava Zhevaha'
          git config --global user.email 'v.zhevaga@gmail.com'
          git remote set-url origin https://x-access-token:${{ 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 }}@github.com/${{ sl101/react-page }}
          npm run deploy
